# Generated by Django 4.2.7 on 2023-11-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
